apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICBzbXRwX3NtYXJ0aG9zdDogJ3NtdHAucXEuY29tOjU4NycKICBzbXRwX2Zyb206ICc4NDY1NjExNjVAcXEuY29tJwogIHNtdHBfYXV0aF91c2VybmFtZTogJzg0NjU2MTE2NUBxcS5jb20nCiAgc210cF9hdXRoX3Bhc3N3b3JkOiAnZ3ZwZ3Jtb2VzYmtoYmVoZycKCnJvdXRlOgogIGdyb3VwX2J5OiBbJ2FsZXJ0bmFtZScsICdjbHVzdGVyJywgJ3NlcnZpY2UnXQogIGdyb3VwX3dhaXQ6IDMwcwogIGdyb3VwX2ludGVydmFsOiA1bQogIHJlcGVhdF9pbnRlcnZhbDogMTVtCiAgcmVjZWl2ZXI6IHRlYW0tWC1tYWlscwogIHJvdXRlczoKICAtIG1hdGNoX3JlOgogICAgICBhbGVydG5hbWU6IF4oaG9zdF9jcHVfdXNhZ2V8bm9kZV9maWxlc3lzdGVtX2ZyZWV8aG9zdF9kb3duKSQKICAgIHJlY2VpdmVyOiB0ZWFtLVgtbWFpbHMKICAgIHJvdXRlczoKICAgIC0gbWF0Y2g6CiAgICAgICAgc2V2ZXJpdHk6IGNyaXRpY2Fs 
